name: testownik
description: Multi-platform revamp of the (in)famous Testownik application
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_tabler_icons: ^1.7.0
  google_fonts: ^6.1.0
  path: ^1.8.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
